config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  resources :links do
    member do
      put "like",    to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end
  root 'links#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  belongs_to :link
end

app/models/link.rb
class Link < ApplicationRecord
  acts_as_votable
  belongs_to :user

  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def checking
    if user_signed_in?
      redirect_to root_path
    else
      redirect_to new_user_session_path
    end
  end
  # def after_sign_up_path_for(resource)
  #   if current_user.type == "linkuser"
  #     links_path
  #   else
  #     urls_path
  #   end
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json

  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
    @link = current_user.links.build
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_back(fallback_location: root_path)
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<%= form_for(comment) do %>
	<div class="comments_wrapper clearfix">
		<div class="pull-left">
			<p class="lead"><%= comment.body %></p>
			<p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.name %></small></p>
		</div>

		<div class="btn-group pull-right">
			<% if comment.user == current_user -%>
				<%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link_id %>
    <%= form.number_field :link_id, id: :comment_link_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :comment_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user.name %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/erb/_header.html.erb
<div class="container-fluid">
  <div class="row menu">
    <ul class="nav nav-tabs">
      <div class="col-md-6">
        <ul class="nav navbar-nav navbar-left">
          <li><%=link_to 'RaddiT', root_path, class: "head" %></li>
        </ul>
       </div>

      <div class="col-md-6">
         <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right ">
              <li><%= link_to 'Submit link', new_link_path, class: "abc"%></li>
              <li><%= link_to 'Account', edit_user_registration_path, class: "abc"%></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, class: "out1 abc", :method => :delete  %></li>
            </ul>
         <% else %>
            <ul class = "nav navbar-nav navbar-right ">
              <li><%= link_to 'Sign up', new_user_registration_path, class: "abc" %></li>
              <li><%= link_to 'Sign in', new_user_session_path, class: "abc" %></li>
            </ul>
         <% end %>
      </div>
     </ul>
   </div>

app/views/erb/index.html.erb
<% @links.each_with_index do |link, index| %>
  <div>
    <% if index.even? %>
      <div class = "row col-md-12">
        <div class = "col-md-6 abc">
          <div class="linke"> <%= link_to link.title, link %><br>
            <!-- <div><i>Submitted by <%= link.user.name %></i></div> -->
          </div>
          <div class="btn-group">
            <a class="btn btn-default btn-sm" href="<%= link.url %>">Visit Link</a>
            <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
             <span class="glyphicon glyphicon-chevron-up"></span>
             Upvote
             <%= link.get_upvotes.size %>
            <% end %>
            <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
             <span class="glyphicon glyphicon-chevron-down">
             Downvote
             <%= link.get_downvotes.size %>
            <% end %>
          </div>
        </div>
        <div class = "col-md-6">
        </div>
      </div>

    <% elsif index.odd? %>
      <div class = "row col-md-12">
        <div class = "col-md-6">
        </div>
        <div class = "col-md-6 abc">
          <div class="linko"><%= link_to link.title, link %><br>
           <!-- <div class="aligno"><i>Submitted by <%= link.user.name %></i></div> -->
          </div>
          <div class="btn-group aligno">
            <a class="btn btn-default btn-sm " href="<%= link.url %>">Visit Link</a>
            <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
              <span class="glyphicon glyphicon-chevron-up"></span>
              Upvote
              <%= link.get_upvotes.size %>
            <% end %>
            <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
              <span class="glyphicon glyphicon-chevron-down">
              Downvote
              <%= link.get_downvotes.size %>
            <% end %>
          </div>
        </div>
      </div>
    <% end%>
  </div>
<% end%>

app/views/erb/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path, class: "btn btn-default btn-sm"%>

app/views/erb/show.html.erb
<div class="page-header link">
  <h1><a href="<%= @link.url %>"><%= @link.title %>
  </a><br> <small class="sml"><i>Submitted by <%= @link.user.name %></i></small></h1>
</div>

<div class="btn-group head">
	<%= link_to 'Visit URL', @link.url, class: "btn btn-primary" %>
</div>


<% if @link.user == current_user -%>
	<div class="btn-group">
		<%= link_to 'Edit', edit_link_path(@link), class: "btn btn-default" %>
		<%= link_to 'Destroy', @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
	</div>
<% end %>
<div class="btn-group pull-right">
      <%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        Upvote
        <%= @link.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-down">
        Downvote
        <%= @link.get_downvotes.size %>
      <% end %>
    </div>
</div>

<h3 class= "comments_title">
  <%= @link.comments.count %>Comments
</h3>

<div class = "comments">
    <%= render :partial => @link.comments %>
</div>
<%= simple_form_for [@link, Comment.new] do |f| %>
  <div class = "field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <br>
  <%= f.submit "Add Comment", class: "btn btn primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application','data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'links/header' %>
    <br><br>
    <div class = "full" >
      <div class = "status">
        <% flash.each do |name, msg| %>
			    <%= content_tag(:div, msg, class: "alert alert-info") %>
		    <% end %>
      </div>
      <div class="container">
        <%= yield %>
      </div>
    </div>
</body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/links/_header.html.haml
.container-fluid
  .row.menu
    %ul.nav.nav-tabs
      .col-md-6
        %ul.nav.navbar-nav.navbar-left
          %li
            = link_to 'RaddiT', root_path, class: "head"
      .col-md-6
        -if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to 'Submit Link', new_link_path, class: "abc"
            %li
              = link_to 'Account', edit_user_registration_path, class: "abc"
            %li
              = link_to 'Sign Out', destroy_user_session_path, class: "abc out1", :method => :delete
        - else
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to 'Sign Up', new_user_registration_path, class: "abc"
            %li
              = link_to 'Sign In', new_user_session_path, class: "abc"          

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.haml
%script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"}
:javascript
  $(document).ready(function(){
      $("#add").click(function(){
          $("#newform").toggle("slow");
      });
  });
#content.center-block
  - @links.each_with_index do |link, index|
    %div
      - if index.even?
        .row.col-md-12
          .col-md-6.abc
            .linke
              = link_to link.title, link
              %br
            .btn-group
              %a.btn.btn-default.btn-sm{:href => "#{link.url}"} Visit Link
              = link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do
                %span.glyphicon.glyphicon-chevron-up
                Upvote
                = link.get_upvotes.size
              = link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do
                %span.glyphicon.glyphicon-chevron-down
                Downvote
                = link.get_downvotes.size
          .col-md-6
      - elsif index.odd?
        .row.col-md-12
          .col-md-6
          .col-md-6.abc
            .linko
              = link_to link.title, link
              %br
            .btn-group.aligno
            %a.btn.btn-default.btn-sm{:href => "#{link.url}"} Visit Link
            = link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do
              %span.glyphicon.glyphicon-chevron-up
              Upvote
              = link.get_upvotes.size
            = link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do
              %span.glyphicon.glyphicon-chevron-down
              Downvote
              = link.get_downvotes.size
  .clearfix
  %br
  %div
    %h3.newlink
      Add Link
      %span#add.glyphicon.glyphicon-chevron-down
    #newform
      &nbsp;&nbsp;
      = render 'form', link: @link

app/views/links/new.html.haml
%h1
  New Link
= render 'form', link: @link

= link_to 'Back', links_path, class: "btn btn-default btn-sm"

app/views/links/show.html.haml
.page-header.link_to
  %h1
    %a{:href => "#{@link.url}"} #{@link.title}
    %br
    %small.sml
      %i
        Submitted by #{@link.user.name}
.btn-grouphead
  = link_to 'Visit Url', @link.url, class: "btn btn-primary"

-if @link.user == current_user
  .btn-group
    = link_to 'Edit', edit_link_path(@link), class: "btn btn-default"
    = link_to 'Destroy', @link, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-default"

.btn-group.pull-right
  = link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do
    %span.glyphicon.glyphicon-chevron-up
    Upvote
    #{@link.get_upvotes.size}
  = link_to dislike_link_path(@link), methid: :put, class: "btn btn-default btn-sm" do
    %span.glyphicon.glyphicon-chevron-down
    Downvote
    #{@link.get_downvotes.size}

%h3.comments_title
  #{@link.comments.count} Comments

.comments
  = render :partial => @link.comments

= simple_form_for [@link, Comment.new] do |f|
  .field
    = f.text_area :body, class: "form-control"
  %br
  = f.submit "Add Comment", class: "btn primary"